name: focus_me
description: "Focus.Me - Gerenciador de rotina e foco diário"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Firebase (núcleo + autenticação + banco de dados)
  firebase_core: ^3.3.0
  firebase_auth: ^5.1.3
  cloud_firestore: ^5.2.1

  # Armazenamento local (modo offline)
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Gráficos (estatísticas de humor e produtividade)
  fl_chart: ^0.68.0

  # Notificações locais
  flutter_local_notifications: ^17.1.2
  timezone: ^0.9.3

  # Detectar se o app está offline/online
  connectivity_plus: ^6.0.3

  # Gerenciamento de estado
  provider: ^6.1.2
  uuid: ^3.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

  # Geração automática de adaptadores Hive
  hive_generator: ^2.0.1
  build_runner: ^2.4.6

flutter:
  uses-material-design: true

  assets:
    - assets/
